name: domain
description: "A new Flutter project."
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: 0.10.1
  riverpod: ^2.6.1
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
