name: domain
description: "Domain layer package for flutter_bloc_architecture (defines entities, use-cases, and repositories interfaces)."
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  riverpod: 3.4.2
  json_annotation: ^4.12.0
  twofold: ^0.2.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

  json_serializable: ^6.14.1